/// The resource `random.RandomBytes` generates random bytes that are intended to be used as a secret, or key. Use this in preference to `random.RandomId` when the output is considered sensitive, and should not be displayed in the CLI.
///
/// ## Example Usage
///
/// ### Typescript
/// ```typescript
/// import * as pulumi from "@pulumi/pulumi";
/// import * as azure from "@pulumi/azure";
/// import * as random from "@pulumi/random";
///
/// const jwtSecretRandomBytes = new random.RandomBytes("jwtSecretRandomBytes", {length: 64});
/// const jwtSecretSecret = new azure.keyvault.Secret("jwtSecretSecret", {
///     keyVaultId: "some-azure-key-vault-id",
///     value: jwtSecretRandomBytes.base64,
/// });
/// ```
/// ### Python
/// ```python
/// import pulumi
/// import pulumi_azure as azure
/// import pulumi_random as random
///
/// jwt_secret_random_bytes = random.RandomBytes("jwtSecretRandomBytes", length=64)
/// jwt_secret_secret = azure.keyvault.Secret("jwtSecretSecret",
///     key_vault_id="some-azure-key-vault-id",
///     value=jwt_secret_random_bytes.base64)
/// ```
/// ### C#
/// ```csharp
/// using System.Collections.Generic;
/// using System.Linq;
/// using Pulumi;
/// using Azure = Pulumi.Azure;
/// using Random = Pulumi.Random;
///
/// return await Deployment.RunAsync(() =>
/// {
///     var jwtSecretRandomBytes = new Random.RandomBytes("jwtSecretRandomBytes", new()
///     {
///         Length = 64,
///     });
///
///     var jwtSecretSecret = new Azure.KeyVault.Secret("jwtSecretSecret", new()
///     {
///         KeyVaultId = "some-azure-key-vault-id",
///         Value = jwtSecretRandomBytes.Base64,
///     });
///
/// });
/// ```
/// ### Go
/// ```go
/// package main
///
/// import (
/// 	"github.com/pulumi/pulumi-azure/sdk/v5/go/azure/keyvault"
/// 	"github.com/pulumi/pulumi-random/sdk/v4/go/random"
/// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
/// )
///
/// func main() {
/// 	pulumi.Run(func(ctx *pulumi.Context) error {
/// 		jwtSecretRandomBytes, err := random.NewRandomBytes(ctx, "jwtSecretRandomBytes", &random.RandomBytesArgs{
/// 			Length: pulumi.Int(64),
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		_, err = keyvault.NewSecret(ctx, "jwtSecretSecret", &keyvault.SecretArgs{
/// 			KeyVaultId: pulumi.String("some-azure-key-vault-id"),
/// 			Value:      jwtSecretRandomBytes.Base64,
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		return nil
/// 	})
/// }
/// ```
/// ### Java
/// ```java
/// package generated_program;
///
/// import com.pulumi.Context;
/// import com.pulumi.Pulumi;
/// import com.pulumi.core.Output;
/// import com.pulumi.random.RandomBytes;
/// import com.pulumi.random.RandomBytesArgs;
/// import com.pulumi.azure.keyvault.Secret;
/// import com.pulumi.azure.keyvault.SecretArgs;
/// import java.util.List;
/// import java.util.ArrayList;
/// import java.util.Map;
/// import java.io.File;
/// import java.nio.file.Files;
/// import java.nio.file.Paths;
///
/// public class App {
///     public static void main(String[] args) {
///         Pulumi.run(App::stack);
///     }
///
///     public static void stack(Context ctx) {
///         var jwtSecretRandomBytes = new RandomBytes("jwtSecretRandomBytes", RandomBytesArgs.builder()        
///             .length(64)
///             .build());
///
///         var jwtSecretSecret = new Secret("jwtSecretSecret", SecretArgs.builder()        
///             .keyVaultId("some-azure-key-vault-id")
///             .value(jwtSecretRandomBytes.base64())
///             .build());
///
///     }
/// }
/// ```
/// ### YAML
/// ```yaml
/// resources:
///   jwtSecretRandomBytes:
///     type: random:RandomBytes
///     properties:
///       length: 64
///   jwtSecretSecret:
///     type: azure:keyvault:Secret
///     properties:
///       keyVaultId: some-azure-key-vault-id
///       value: ${jwtSecretRandomBytes.base64}
/// ```
///
/// ## Import
///
/// Random bytes can be imported by specifying the value as base64 string.
///
/// ```sh
///  $ pulumi import random:index/randomBytes:RandomBytes basic "8/fu3q+2DcgSJ19i0jZ5Cw=="
/// ```
///
///  
pub mod random_bytes {

    pub struct RandomBytesArgs {
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        pub keepers: pulumi_wasm_rust::Output<Option<std::collections::HashMap<String, String>>>,
        /// The number of bytes requested. The minimum value for length is 1.
        pub length: pulumi_wasm_rust::Output<i32>,
    }

    pub struct RandomBytesResult {
        /// The generated bytes presented in base64 string format.
        pub base64: pulumi_wasm_rust::Output<String>,
        /// The generated bytes presented in hex string format.
        pub hex: pulumi_wasm_rust::Output<String>,
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        pub keepers: pulumi_wasm_rust::Output<Option<std::collections::HashMap<String, String>>>,
        /// The number of bytes requested. The minimum value for length is 1.
        pub length: pulumi_wasm_rust::Output<i32>,
    }

    ///
    /// Registers a new resource with the given unique name and arguments
    ///
    pub fn random_bytes(name: &str, args: RandomBytesArgs) -> RandomBytesResult {
        let result = crate::bindings::pulumi::random::random_bytes::invoke(
            name,
            &crate::bindings::pulumi::random::random_bytes::Args {
                keepers: args.keepers.get_inner(),
                length: args.length.get_inner(),
            },
        );

        RandomBytesResult {
            base64: crate::into_domain(result.base64),
            hex: crate::into_domain(result.hex),
            keepers: crate::into_domain(result.keepers),
            length: crate::into_domain(result.length),
        }
    }
}

/// The resource `random.RandomId` generates random numbers that are intended to be
/// used as unique identifiers for other resources. If the output is considered
/// sensitive, and should not be displayed in the CLI, use `random.RandomBytes`
/// instead.
///
/// This resource *does* use a cryptographic random number generator in order
/// to minimize the chance of collisions, making the results of this resource
/// when a 16-byte identifier is requested of equivalent uniqueness to a
/// type-4 UUID.
///
/// This resource can be used in conjunction with resources that have
/// the `create_before_destroy` lifecycle flag set to avoid conflicts with
/// unique names during the brief period where both the old and new resources
/// exist concurrently.
///
/// ## Example Usage
///
/// ### Typescript
/// ```typescript
/// import * as pulumi from "@pulumi/pulumi";
/// import * as aws from "@pulumi/aws";
/// import * as random from "@pulumi/random";
///
/// // The following example shows how to generate a unique name for an AWS EC2
/// // instance that changes each time a new AMI id is selected.
/// const serverRandomId = new random.RandomId("serverRandomId", {
///     keepers: {
///         ami_id: _var.ami_id,
///     },
///     byteLength: 8,
/// });
/// const serverInstance = new aws.ec2.Instance("serverInstance", {
///     tags: {
///         Name: pulumi.interpolate`web-server ${serverRandomId.hex}`,
///     },
///     ami: serverRandomId.keepers.apply(keepers => keepers?.amiId),
/// });
/// // ... (other aws_instance arguments) ...
/// ```
/// ### Python
/// ```python
/// import pulumi
/// import pulumi_aws as aws
/// import pulumi_random as random
///
/// # The following example shows how to generate a unique name for an AWS EC2
/// # instance that changes each time a new AMI id is selected.
/// server_random_id = random.RandomId("serverRandomId",
///     keepers={
///         "ami_id": var["ami_id"],
///     },
///     byte_length=8)
/// server_instance = aws.ec2.Instance("serverInstance",
///     tags={
///         "Name": server_random_id.hex.apply(lambda hex: f"web-server {hex}"),
///     },
///     ami=server_random_id.keepers["amiId"])
/// # ... (other aws_instance arguments) ...
/// ```
/// ### C#
/// ```csharp
/// using System.Collections.Generic;
/// using System.Linq;
/// using Pulumi;
/// using Aws = Pulumi.Aws;
/// using Random = Pulumi.Random;
///
/// return await Deployment.RunAsync(() =>
/// {
///     // The following example shows how to generate a unique name for an AWS EC2
///     // instance that changes each time a new AMI id is selected.
///     var serverRandomId = new Random.RandomId("serverRandomId", new()
///     {
///         Keepers =
///         {
///             { "ami_id", @var.Ami_id },
///         },
///         ByteLength = 8,
///     });
///
///     var serverInstance = new Aws.Ec2.Instance("serverInstance", new()
///     {
///         Tags =
///         {
///             { "Name", serverRandomId.Hex.Apply(hex => $"web-server {hex}") },
///         },
///         Ami = serverRandomId.Keepers.Apply(keepers => keepers?.AmiId),
///     });
///
///     // ... (other aws_instance arguments) ...
/// });
/// ```
/// ### Go
/// ```go
/// package main
///
/// import (
/// 	"fmt"
///
/// 	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ec2"
/// 	"github.com/pulumi/pulumi-random/sdk/v4/go/random"
/// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
/// )
///
/// func main() {
/// 	pulumi.Run(func(ctx *pulumi.Context) error {
/// 		serverRandomId, err := random.NewRandomId(ctx, "serverRandomId", &random.RandomIdArgs{
/// 			Keepers: pulumi.StringMap{
/// 				"ami_id": pulumi.Any(_var.Ami_id),
/// 			},
/// 			ByteLength: pulumi.Int(8),
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		_, err = ec2.NewInstance(ctx, "serverInstance", &ec2.InstanceArgs{
/// 			Tags: pulumi.StringMap{
/// 				"Name": serverRandomId.Hex.ApplyT(func(hex string) (string, error) {
/// 					return fmt.Sprintf("web-server %v", hex), nil
/// 				}).(pulumi.StringOutput),
/// 			},
/// 			Ami: serverRandomId.Keepers.ApplyT(func(keepers interface{}) (*string, error) {
/// 				return &keepers.AmiId, nil
/// 			}).(pulumi.StringPtrOutput),
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		return nil
/// 	})
/// }
/// ```
/// ### Java
/// ```java
/// package generated_program;
///
/// import com.pulumi.Context;
/// import com.pulumi.Pulumi;
/// import com.pulumi.core.Output;
/// import com.pulumi.random.RandomId;
/// import com.pulumi.random.RandomIdArgs;
/// import com.pulumi.aws.ec2.Instance;
/// import com.pulumi.aws.ec2.InstanceArgs;
/// import java.util.List;
/// import java.util.ArrayList;
/// import java.util.Map;
/// import java.io.File;
/// import java.nio.file.Files;
/// import java.nio.file.Paths;
///
/// public class App {
///     public static void main(String[] args) {
///         Pulumi.run(App::stack);
///     }
///
///     public static void stack(Context ctx) {
///         var serverRandomId = new RandomId("serverRandomId", RandomIdArgs.builder()        
///             .keepers(Map.of("ami_id", var_.ami_id()))
///             .byteLength(8)
///             .build());
///
///         var serverInstance = new Instance("serverInstance", InstanceArgs.builder()        
///             .tags(Map.of("Name", serverRandomId.hex().applyValue(hex -> String.format("web-server %s", hex))))
///             .ami(serverRandomId.keepers().applyValue(keepers -> keepers.amiId()))
///             .build());
///
///     }
/// }
/// ```
/// ### YAML
/// ```yaml
/// resources:
///   # The following example shows how to generate a unique name for an AWS EC2
///   # instance that changes each time a new AMI id is selected.
///   serverRandomId:
///     type: random:RandomId
///     properties:
///       keepers:
///         ami_id: ${var.ami_id}
///       byteLength: 8
///   serverInstance:
///     type: aws:ec2:Instance
///     properties:
///       tags:
///         Name: web-server ${serverRandomId.hex}
///       # Read the AMI id "through" the random_id resource to ensure that
///       #   # both will change together.
///       ami: ${serverRandomId.keepers.amiId}
/// ```
///
/// ## Import
///
/// Random IDs can be imported using the b64_url with an optional prefix. This can be used to replace a config value with a value interpolated from the random provider without experiencing diffs. Example with no prefix
///
/// ```sh
///  $ pulumi import random:index/randomId:RandomId server p-9hUg
/// ```
///
///  Example with prefix (prefix is separated by a ,)
///
/// ```sh
///  $ pulumi import random:index/randomId:RandomId server my-prefix-,p-9hUg
/// ```
///
///  
pub mod random_id {

    pub struct RandomIdArgs {
        /// The number of random bytes to produce. The minimum value is 1, which produces eight bits of randomness.
        pub byte_length: pulumi_wasm_rust::Output<i32>,
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        pub keepers: pulumi_wasm_rust::Output<Option<std::collections::HashMap<String, String>>>,
        /// Arbitrary string to prefix the output value with. This string is supplied as-is, meaning it is not guaranteed to be URL-safe or base64 encoded.
        pub prefix: pulumi_wasm_rust::Output<Option<String>>,
    }

    pub struct RandomIdResult {
        /// The generated id presented in base64 without additional transformations.
        pub b64_std: pulumi_wasm_rust::Output<String>,
        /// The generated id presented in base64, using the URL-friendly character set: case-sensitive letters, digits and the characters `_` and `-`.
        pub b64_url: pulumi_wasm_rust::Output<String>,
        /// The number of random bytes to produce. The minimum value is 1, which produces eight bits of randomness.
        pub byte_length: pulumi_wasm_rust::Output<i32>,
        /// The generated id presented in non-padded decimal digits.
        pub dec: pulumi_wasm_rust::Output<String>,
        /// The generated id presented in padded hexadecimal digits. This result will always be twice as long as the requested byte length.
        pub hex: pulumi_wasm_rust::Output<String>,
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        pub keepers: pulumi_wasm_rust::Output<Option<std::collections::HashMap<String, String>>>,
        /// Arbitrary string to prefix the output value with. This string is supplied as-is, meaning it is not guaranteed to be URL-safe or base64 encoded.
        pub prefix: pulumi_wasm_rust::Output<Option<String>>,
    }

    ///
    /// Registers a new resource with the given unique name and arguments
    ///
    pub fn random_id(name: &str, args: RandomIdArgs) -> RandomIdResult {
        let result = crate::bindings::pulumi::random::random_id::invoke(
            name,
            &crate::bindings::pulumi::random::random_id::Args {
                byte_length: args.byte_length.get_inner(),
                keepers: args.keepers.get_inner(),
                prefix: args.prefix.get_inner(),
            },
        );

        RandomIdResult {
            b64_std: crate::into_domain(result.b64_std),
            b64_url: crate::into_domain(result.b64_url),
            byte_length: crate::into_domain(result.byte_length),
            dec: crate::into_domain(result.dec),
            hex: crate::into_domain(result.hex),
            keepers: crate::into_domain(result.keepers),
            prefix: crate::into_domain(result.prefix),
        }
    }
}

/// The resource `random.RandomInteger` generates random values from a given range, described by the `min` and `max` attributes of a given resource.
///
/// This resource can be used in conjunction with resources that have the `create_before_destroy` lifecycle flag set, to avoid conflicts with unique names during the brief period where both the old and new resources exist concurrently.
///
/// ## Example Usage
///
/// ### Typescript
/// ```typescript
/// import * as pulumi from "@pulumi/pulumi";
/// import * as aws from "@pulumi/aws";
/// import * as random from "@pulumi/random";
///
/// // The following example shows how to generate a random priority
/// // between 1 and 50000 for a aws_alb_listener_rule resource:
/// const priority = new random.RandomInteger("priority", {
///     min: 1,
///     max: 50000,
///     keepers: {
///         listener_arn: _var.listener_arn,
///     },
/// });
/// const main = new aws.alb.ListenerRule("main", {
///     listenerArn: priority.keepers.apply(keepers => keepers?.listenerArn),
///     priority: priority.result,
///     actions: [{
///         type: "forward",
///         targetGroupArn: _var.target_group_arn,
///     }],
/// });
/// // ... (other aws_alb_listener_rule arguments) ...
/// ```
/// ### Python
/// ```python
/// import pulumi
/// import pulumi_aws as aws
/// import pulumi_random as random
///
/// # The following example shows how to generate a random priority
/// # between 1 and 50000 for a aws_alb_listener_rule resource:
/// priority = random.RandomInteger("priority",
///     min=1,
///     max=50000,
///     keepers={
///         "listener_arn": var["listener_arn"],
///     })
/// main = aws.alb.ListenerRule("main",
///     listener_arn=priority.keepers["listenerArn"],
///     priority=priority.result,
///     actions=[aws.alb.ListenerRuleActionArgs(
///         type="forward",
///         target_group_arn=var["target_group_arn"],
///     )])
/// # ... (other aws_alb_listener_rule arguments) ...
/// ```
/// ### C#
/// ```csharp
/// using System.Collections.Generic;
/// using System.Linq;
/// using Pulumi;
/// using Aws = Pulumi.Aws;
/// using Random = Pulumi.Random;
///
/// return await Deployment.RunAsync(() =>
/// {
///     // The following example shows how to generate a random priority
///     // between 1 and 50000 for a aws_alb_listener_rule resource:
///     var priority = new Random.RandomInteger("priority", new()
///     {
///         Min = 1,
///         Max = 50000,
///         Keepers =
///         {
///             { "listener_arn", @var.Listener_arn },
///         },
///     });
///
///     var main = new Aws.Alb.ListenerRule("main", new()
///     {
///         ListenerArn = priority.Keepers.Apply(keepers => keepers?.ListenerArn),
///         Priority = priority.Result,
///         Actions = new[]
///         {
///             new Aws.Alb.Inputs.ListenerRuleActionArgs
///             {
///                 Type = "forward",
///                 TargetGroupArn = @var.Target_group_arn,
///             },
///         },
///     });
///
///     // ... (other aws_alb_listener_rule arguments) ...
/// });
/// ```
/// ### Go
/// ```go
/// package main
///
/// import (
/// 	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/alb"
/// 	"github.com/pulumi/pulumi-random/sdk/v4/go/random"
/// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
/// )
///
/// func main() {
/// 	pulumi.Run(func(ctx *pulumi.Context) error {
/// 		priority, err := random.NewRandomInteger(ctx, "priority", &random.RandomIntegerArgs{
/// 			Min: pulumi.Int(1),
/// 			Max: pulumi.Int(50000),
/// 			Keepers: pulumi.StringMap{
/// 				"listener_arn": pulumi.Any(_var.Listener_arn),
/// 			},
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		_, err = alb.NewListenerRule(ctx, "main", &alb.ListenerRuleArgs{
/// 			ListenerArn: priority.Keepers.ApplyT(func(keepers interface{}) (*string, error) {
/// 				return &keepers.ListenerArn, nil
/// 			}).(pulumi.StringPtrOutput),
/// 			Priority: priority.Result,
/// 			Actions: alb.ListenerRuleActionArray{
/// 				&alb.ListenerRuleActionArgs{
/// 					Type:           pulumi.String("forward"),
/// 					TargetGroupArn: pulumi.Any(_var.Target_group_arn),
/// 				},
/// 			},
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		return nil
/// 	})
/// }
/// ```
/// ### Java
/// ```java
/// package generated_program;
///
/// import com.pulumi.Context;
/// import com.pulumi.Pulumi;
/// import com.pulumi.core.Output;
/// import com.pulumi.random.RandomInteger;
/// import com.pulumi.random.RandomIntegerArgs;
/// import com.pulumi.aws.alb.ListenerRule;
/// import com.pulumi.aws.alb.ListenerRuleArgs;
/// import com.pulumi.aws.alb.inputs.ListenerRuleActionArgs;
/// import java.util.List;
/// import java.util.ArrayList;
/// import java.util.Map;
/// import java.io.File;
/// import java.nio.file.Files;
/// import java.nio.file.Paths;
///
/// public class App {
///     public static void main(String[] args) {
///         Pulumi.run(App::stack);
///     }
///
///     public static void stack(Context ctx) {
///         var priority = new RandomInteger("priority", RandomIntegerArgs.builder()        
///             .min(1)
///             .max(50000)
///             .keepers(Map.of("listener_arn", var_.listener_arn()))
///             .build());
///
///         var main = new ListenerRule("main", ListenerRuleArgs.builder()        
///             .listenerArn(priority.keepers().applyValue(keepers -> keepers.listenerArn()))
///             .priority(priority.result())
///             .actions(ListenerRuleActionArgs.builder()
///                 .type("forward")
///                 .targetGroupArn(var_.target_group_arn())
///                 .build())
///             .build());
///
///     }
/// }
/// ```
/// ### YAML
/// ```yaml
/// resources:
///   # The following example shows how to generate a random priority
///   # between 1 and 50000 for a aws_alb_listener_rule resource:
///   priority:
///     type: random:RandomInteger
///     properties:
///       min: 1
///       max: 50000
///       keepers:
///         listener_arn: ${var.listener_arn}
///   main:
///     type: aws:alb:ListenerRule
///     properties:
///       listenerArn: ${priority.keepers.listenerArn}
///       priority: ${priority.result}
///       actions:
///         - type: forward
///           targetGroupArn: ${var.target_group_arn}
/// ```
///
/// ## Import
///
/// Random integers can be imported using the result, min, and max, with an optional seed. This can be used to replace a config value with a value interpolated from the random provider without experiencing diffs. Example (values are separated by a ,)
///
/// ```sh
///  $ pulumi import random:index/randomInteger:RandomInteger priority 15390,1,50000
/// ```
///
///  
pub mod random_integer {

    pub struct RandomIntegerArgs {
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        pub keepers: pulumi_wasm_rust::Output<Option<std::collections::HashMap<String, String>>>,
        /// The maximum inclusive value of the range.
        pub max: pulumi_wasm_rust::Output<i32>,
        /// The minimum inclusive value of the range.
        pub min: pulumi_wasm_rust::Output<i32>,
        /// A custom seed to always produce the same value.
        pub seed: pulumi_wasm_rust::Output<Option<String>>,
    }

    pub struct RandomIntegerResult {
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        pub keepers: pulumi_wasm_rust::Output<Option<std::collections::HashMap<String, String>>>,
        /// The maximum inclusive value of the range.
        pub max: pulumi_wasm_rust::Output<i32>,
        /// The minimum inclusive value of the range.
        pub min: pulumi_wasm_rust::Output<i32>,
        /// The random integer result.
        pub result: pulumi_wasm_rust::Output<i32>,
        /// A custom seed to always produce the same value.
        pub seed: pulumi_wasm_rust::Output<Option<String>>,
    }

    ///
    /// Registers a new resource with the given unique name and arguments
    ///
    pub fn random_integer(name: &str, args: RandomIntegerArgs) -> RandomIntegerResult {
        let result = crate::bindings::pulumi::random::random_integer::invoke(
            name,
            &crate::bindings::pulumi::random::random_integer::Args {
                keepers: args.keepers.get_inner(),
                max: args.max.get_inner(),
                min: args.min.get_inner(),
                seed: args.seed.get_inner(),
            },
        );

        RandomIntegerResult {
            keepers: crate::into_domain(result.keepers),
            max: crate::into_domain(result.max),
            min: crate::into_domain(result.min),
            result: crate::into_domain(result.result),
            seed: crate::into_domain(result.seed),
        }
    }
}

/// Identical to random_string.
///
/// This resource *does* use a cryptographic random number generator.
///
/// ## Example Usage
///
/// ### Typescript
/// ```typescript
/// import * as pulumi from "@pulumi/pulumi";
/// import * as aws from "@pulumi/aws";
/// import * as random from "@pulumi/random";
///
/// const password = new random.RandomPassword("password", {
///     length: 16,
///     special: true,
///     overrideSpecial: "!#$%&*()-_=+[]{}<>:?",
/// });
/// const example = new aws.rds.Instance("example", {
///     instanceClass: "db.t3.micro",
///     allocatedStorage: 64,
///     engine: "mysql",
///     username: "someone",
///     password: password.result,
/// });
/// ```
/// ### Python
/// ```python
/// import pulumi
/// import pulumi_aws as aws
/// import pulumi_random as random
///
/// password = random.RandomPassword("password",
///     length=16,
///     special=True,
///     override_special="!#$%&*()-_=+[]{}<>:?")
/// example = aws.rds.Instance("example",
///     instance_class="db.t3.micro",
///     allocated_storage=64,
///     engine="mysql",
///     username="someone",
///     password=password.result)
/// ```
/// ### C#
/// ```csharp
/// using System.Collections.Generic;
/// using System.Linq;
/// using Pulumi;
/// using Aws = Pulumi.Aws;
/// using Random = Pulumi.Random;
///
/// return await Deployment.RunAsync(() =>
/// {
///     var password = new Random.RandomPassword("password", new()
///     {
///         Length = 16,
///         Special = true,
///         OverrideSpecial = "!#$%&*()-_=+[]{}<>:?",
///     });
///
///     var example = new Aws.Rds.Instance("example", new()
///     {
///         InstanceClass = "db.t3.micro",
///         AllocatedStorage = 64,
///         Engine = "mysql",
///         Username = "someone",
///         Password = password.Result,
///     });
///
/// });
/// ```
/// ### Go
/// ```go
/// package main
///
/// import (
/// 	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/rds"
/// 	"github.com/pulumi/pulumi-random/sdk/v4/go/random"
/// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
/// )
///
/// func main() {
/// 	pulumi.Run(func(ctx *pulumi.Context) error {
/// 		password, err := random.NewRandomPassword(ctx, "password", &random.RandomPasswordArgs{
/// 			Length:          pulumi.Int(16),
/// 			Special:         pulumi.Bool(true),
/// 			OverrideSpecial: pulumi.String("!#$%&*()-_=+[]{}<>:?"),
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		_, err = rds.NewInstance(ctx, "example", &rds.InstanceArgs{
/// 			InstanceClass:    pulumi.String("db.t3.micro"),
/// 			AllocatedStorage: pulumi.Int(64),
/// 			Engine:           pulumi.String("mysql"),
/// 			Username:         pulumi.String("someone"),
/// 			Password:         password.Result,
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		return nil
/// 	})
/// }
/// ```
/// ### Java
/// ```java
/// package generated_program;
///
/// import com.pulumi.Context;
/// import com.pulumi.Pulumi;
/// import com.pulumi.core.Output;
/// import com.pulumi.random.RandomPassword;
/// import com.pulumi.random.RandomPasswordArgs;
/// import com.pulumi.aws.rds.Instance;
/// import com.pulumi.aws.rds.InstanceArgs;
/// import java.util.List;
/// import java.util.ArrayList;
/// import java.util.Map;
/// import java.io.File;
/// import java.nio.file.Files;
/// import java.nio.file.Paths;
///
/// public class App {
///     public static void main(String[] args) {
///         Pulumi.run(App::stack);
///     }
///
///     public static void stack(Context ctx) {
///         var password = new RandomPassword("password", RandomPasswordArgs.builder()        
///             .length(16)
///             .special(true)
///             .overrideSpecial("!#$%&*()-_=+[]{}<>:?")
///             .build());
///
///         var example = new Instance("example", InstanceArgs.builder()        
///             .instanceClass("db.t3.micro")
///             .allocatedStorage(64)
///             .engine("mysql")
///             .username("someone")
///             .password(password.result())
///             .build());
///
///     }
/// }
/// ```
/// ### YAML
/// ```yaml
/// resources:
///   password:
///     type: random:RandomPassword
///     properties:
///       length: 16
///       special: true
///       overrideSpecial: '!#$%&*()-_=+[]{}<>:?'
///   example:
///     type: aws:rds:Instance
///     properties:
///       instanceClass: db.t3.micro
///       allocatedStorage: 64
///       engine: mysql
///       username: someone
///       password: ${password.result}
/// ```
///
/// ## Import
///
/// You can import external passwords into your Pulumi programs as follows:
///
/// ```sh
///  $ import random:index/randomPassword:RandomPassword newPassword supersecret
/// ```
///
/// This command will encode the `supersecret` token in Pulumi state and generate a code suggestion to include a new RandomPassword resource in your Pulumi program. Include the suggested code and do a `pulumi up`. Your secret password is now securely stored in Pulumi, and you can reference it in your Pulumi program as `newPassword.result`.
pub mod random_password {

    pub struct RandomPasswordArgs {
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        pub keepers: pulumi_wasm_rust::Output<Option<std::collections::HashMap<String, String>>>,
        /// The length of the string desired. The minimum value for length is 1 and, length must also be >= (`min_upper` + `min_lower` + `min_numeric` + `min_special`).
        pub length: pulumi_wasm_rust::Output<i32>,
        /// Include lowercase alphabet characters in the result. Default value is `true`.
        pub lower: pulumi_wasm_rust::Output<Option<bool>>,
        /// Minimum number of lowercase alphabet characters in the result. Default value is `0`.
        pub min_lower: pulumi_wasm_rust::Output<Option<i32>>,
        /// Minimum number of numeric characters in the result. Default value is `0`.
        pub min_numeric: pulumi_wasm_rust::Output<Option<i32>>,
        /// Minimum number of special characters in the result. Default value is `0`.
        pub min_special: pulumi_wasm_rust::Output<Option<i32>>,
        /// Minimum number of uppercase alphabet characters in the result. Default value is `0`.
        pub min_upper: pulumi_wasm_rust::Output<Option<i32>>,
        /// Include numeric characters in the result. Default value is `true`. **NOTE**: This is deprecated, use `numeric` instead.
        pub number: pulumi_wasm_rust::Output<Option<bool>>,
        /// Include numeric characters in the result. Default value is `true`.
        pub numeric: pulumi_wasm_rust::Output<Option<bool>>,
        /// Supply your own list of special characters to use for string generation.  This overrides the default character list in the special argument.  The `special` argument must still be set to true for any overwritten characters to be used in generation.
        pub override_special: pulumi_wasm_rust::Output<Option<String>>,
        /// Include special characters in the result. These are `!@#$%&*()-_=+[]{}<>:?`. Default value is `true`.
        pub special: pulumi_wasm_rust::Output<Option<bool>>,
        /// Include uppercase alphabet characters in the result. Default value is `true`.
        pub upper: pulumi_wasm_rust::Output<Option<bool>>,
    }

    pub struct RandomPasswordResult {
        /// A bcrypt hash of the generated random string. **NOTE**: If the generated random string is greater than 72 bytes in length, `bcrypt_hash` will contain a hash of the first 72 bytes.
        pub bcrypt_hash: pulumi_wasm_rust::Output<String>,
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        pub keepers: pulumi_wasm_rust::Output<Option<std::collections::HashMap<String, String>>>,
        /// The length of the string desired. The minimum value for length is 1 and, length must also be >= (`min_upper` + `min_lower` + `min_numeric` + `min_special`).
        pub length: pulumi_wasm_rust::Output<i32>,
        /// Include lowercase alphabet characters in the result. Default value is `true`.
        pub lower: pulumi_wasm_rust::Output<bool>,
        /// Minimum number of lowercase alphabet characters in the result. Default value is `0`.
        pub min_lower: pulumi_wasm_rust::Output<i32>,
        /// Minimum number of numeric characters in the result. Default value is `0`.
        pub min_numeric: pulumi_wasm_rust::Output<i32>,
        /// Minimum number of special characters in the result. Default value is `0`.
        pub min_special: pulumi_wasm_rust::Output<i32>,
        /// Minimum number of uppercase alphabet characters in the result. Default value is `0`.
        pub min_upper: pulumi_wasm_rust::Output<i32>,
        /// Include numeric characters in the result. Default value is `true`. **NOTE**: This is deprecated, use `numeric` instead.
        pub number: pulumi_wasm_rust::Output<bool>,
        /// Include numeric characters in the result. Default value is `true`.
        pub numeric: pulumi_wasm_rust::Output<bool>,
        /// Supply your own list of special characters to use for string generation.  This overrides the default character list in the special argument.  The `special` argument must still be set to true for any overwritten characters to be used in generation.
        pub override_special: pulumi_wasm_rust::Output<Option<String>>,
        /// The generated random string.
        pub result: pulumi_wasm_rust::Output<String>,
        /// Include special characters in the result. These are `!@#$%&*()-_=+[]{}<>:?`. Default value is `true`.
        pub special: pulumi_wasm_rust::Output<bool>,
        /// Include uppercase alphabet characters in the result. Default value is `true`.
        pub upper: pulumi_wasm_rust::Output<bool>,
    }

    ///
    /// Registers a new resource with the given unique name and arguments
    ///
    pub fn random_password(name: &str, args: RandomPasswordArgs) -> RandomPasswordResult {
        let result = crate::bindings::pulumi::random::random_password::invoke(
            name,
            &crate::bindings::pulumi::random::random_password::Args {
                keepers: args.keepers.get_inner(),
                length: args.length.get_inner(),
                lower: args.lower.get_inner(),
                min_lower: args.min_lower.get_inner(),
                min_numeric: args.min_numeric.get_inner(),
                min_special: args.min_special.get_inner(),
                min_upper: args.min_upper.get_inner(),
                number: args.number.get_inner(),
                numeric: args.numeric.get_inner(),
                override_special: args.override_special.get_inner(),
                special: args.special.get_inner(),
                upper: args.upper.get_inner(),
            },
        );

        RandomPasswordResult {
            bcrypt_hash: crate::into_domain(result.bcrypt_hash),
            keepers: crate::into_domain(result.keepers),
            length: crate::into_domain(result.length),
            lower: crate::into_domain(result.lower),
            min_lower: crate::into_domain(result.min_lower),
            min_numeric: crate::into_domain(result.min_numeric),
            min_special: crate::into_domain(result.min_special),
            min_upper: crate::into_domain(result.min_upper),
            number: crate::into_domain(result.number),
            numeric: crate::into_domain(result.numeric),
            override_special: crate::into_domain(result.override_special),
            result: crate::into_domain(result.result),
            special: crate::into_domain(result.special),
            upper: crate::into_domain(result.upper),
        }
    }
}

/// The resource `random.RandomPet` generates random pet names that are intended to be used as unique identifiers for other resources.
///
/// This resource can be used in conjunction with resources that have the `create_before_destroy` lifecycle flag set, to avoid conflicts with unique names during the brief period where both the old and new resources exist concurrently.
///
/// ## Example Usage
///
/// ### Typescript
/// ```typescript
/// import * as pulumi from "@pulumi/pulumi";
/// import * as aws from "@pulumi/aws";
/// import * as random from "@pulumi/random";
///
/// // The following example shows how to generate a unique pet name
/// // for an AWS EC2 instance that changes each time a new AMI id is
/// // selected.
/// const serverRandomPet = new random.RandomPet("serverRandomPet", {keepers: {
///     ami_id: _var.ami_id,
/// }});
/// const serverInstance = new aws.ec2.Instance("serverInstance", {
///     tags: {
///         Name: pulumi.interpolate`web-server-${serverRandomPet.id}`,
///     },
///     ami: serverRandomPet.keepers.apply(keepers => keepers?.amiId),
/// });
/// // ... (other aws_instance arguments) ...
/// ```
/// ### Python
/// ```python
/// import pulumi
/// import pulumi_aws as aws
/// import pulumi_random as random
///
/// # The following example shows how to generate a unique pet name
/// # for an AWS EC2 instance that changes each time a new AMI id is
/// # selected.
/// server_random_pet = random.RandomPet("serverRandomPet", keepers={
///     "ami_id": var["ami_id"],
/// })
/// server_instance = aws.ec2.Instance("serverInstance",
///     tags={
///         "Name": server_random_pet.id.apply(lambda id: f"web-server-{id}"),
///     },
///     ami=server_random_pet.keepers["amiId"])
/// # ... (other aws_instance arguments) ...
/// ```
/// ### C#
/// ```csharp
/// using System.Collections.Generic;
/// using System.Linq;
/// using Pulumi;
/// using Aws = Pulumi.Aws;
/// using Random = Pulumi.Random;
///
/// return await Deployment.RunAsync(() =>
/// {
///     // The following example shows how to generate a unique pet name
///     // for an AWS EC2 instance that changes each time a new AMI id is
///     // selected.
///     var serverRandomPet = new Random.RandomPet("serverRandomPet", new()
///     {
///         Keepers =
///         {
///             { "ami_id", @var.Ami_id },
///         },
///     });
///
///     var serverInstance = new Aws.Ec2.Instance("serverInstance", new()
///     {
///         Tags =
///         {
///             { "Name", serverRandomPet.Id.Apply(id => $"web-server-{id}") },
///         },
///         Ami = serverRandomPet.Keepers.Apply(keepers => keepers?.AmiId),
///     });
///
///     // ... (other aws_instance arguments) ...
/// });
/// ```
/// ### Go
/// ```go
/// package main
///
/// import (
/// 	"fmt"
///
/// 	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ec2"
/// 	"github.com/pulumi/pulumi-random/sdk/v4/go/random"
/// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
/// )
///
/// func main() {
/// 	pulumi.Run(func(ctx *pulumi.Context) error {
/// 		serverRandomPet, err := random.NewRandomPet(ctx, "serverRandomPet", &random.RandomPetArgs{
/// 			Keepers: pulumi.StringMap{
/// 				"ami_id": pulumi.Any(_var.Ami_id),
/// 			},
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		_, err = ec2.NewInstance(ctx, "serverInstance", &ec2.InstanceArgs{
/// 			Tags: pulumi.StringMap{
/// 				"Name": serverRandomPet.ID().ApplyT(func(id string) (string, error) {
/// 					return fmt.Sprintf("web-server-%v", id), nil
/// 				}).(pulumi.StringOutput),
/// 			},
/// 			Ami: serverRandomPet.Keepers.ApplyT(func(keepers interface{}) (*string, error) {
/// 				return &keepers.AmiId, nil
/// 			}).(pulumi.StringPtrOutput),
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		return nil
/// 	})
/// }
/// ```
/// ### Java
/// ```java
/// package generated_program;
///
/// import com.pulumi.Context;
/// import com.pulumi.Pulumi;
/// import com.pulumi.core.Output;
/// import com.pulumi.random.RandomPet;
/// import com.pulumi.random.RandomPetArgs;
/// import com.pulumi.aws.ec2.Instance;
/// import com.pulumi.aws.ec2.InstanceArgs;
/// import java.util.List;
/// import java.util.ArrayList;
/// import java.util.Map;
/// import java.io.File;
/// import java.nio.file.Files;
/// import java.nio.file.Paths;
///
/// public class App {
///     public static void main(String[] args) {
///         Pulumi.run(App::stack);
///     }
///
///     public static void stack(Context ctx) {
///         var serverRandomPet = new RandomPet("serverRandomPet", RandomPetArgs.builder()        
///             .keepers(Map.of("ami_id", var_.ami_id()))
///             .build());
///
///         var serverInstance = new Instance("serverInstance", InstanceArgs.builder()        
///             .tags(Map.of("Name", serverRandomPet.id().applyValue(id -> String.format("web-server-%s", id))))
///             .ami(serverRandomPet.keepers().applyValue(keepers -> keepers.amiId()))
///             .build());
///
///     }
/// }
/// ```
/// ### YAML
/// ```yaml
/// resources:
///   # The following example shows how to generate a unique pet name
///   # for an AWS EC2 instance that changes each time a new AMI id is
///   # selected.
///   serverRandomPet:
///     type: random:RandomPet
///     properties:
///       keepers:
///         ami_id: ${var.ami_id}
///   serverInstance:
///     type: aws:ec2:Instance
///     properties:
///       tags:
///         Name: web-server-${serverRandomPet.id}
///       # Read the AMI id "through" the random_pet resource to ensure that
///       #   # both will change together.
///       ami: ${serverRandomPet.keepers.amiId}
/// ```
pub mod random_pet {

    pub struct RandomPetArgs {
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        pub keepers: pulumi_wasm_rust::Output<Option<std::collections::HashMap<String, String>>>,
        /// The length (in words) of the pet name. Defaults to 2
        pub length: pulumi_wasm_rust::Output<Option<i32>>,
        /// A string to prefix the name with.
        pub prefix: pulumi_wasm_rust::Output<Option<String>>,
        /// The character to separate words in the pet name. Defaults to "-"
        pub separator: pulumi_wasm_rust::Output<Option<String>>,
    }

    pub struct RandomPetResult {
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        pub keepers: pulumi_wasm_rust::Output<Option<std::collections::HashMap<String, String>>>,
        /// The length (in words) of the pet name. Defaults to 2
        pub length: pulumi_wasm_rust::Output<i32>,
        /// A string to prefix the name with.
        pub prefix: pulumi_wasm_rust::Output<Option<String>>,
        /// The character to separate words in the pet name. Defaults to "-"
        pub separator: pulumi_wasm_rust::Output<String>,
    }

    ///
    /// Registers a new resource with the given unique name and arguments
    ///
    pub fn random_pet(name: &str, args: RandomPetArgs) -> RandomPetResult {
        let result = crate::bindings::pulumi::random::random_pet::invoke(
            name,
            &crate::bindings::pulumi::random::random_pet::Args {
                keepers: args.keepers.get_inner(),
                length: args.length.get_inner(),
                prefix: args.prefix.get_inner(),
                separator: args.separator.get_inner(),
            },
        );

        RandomPetResult {
            keepers: crate::into_domain(result.keepers),
            length: crate::into_domain(result.length),
            prefix: crate::into_domain(result.prefix),
            separator: crate::into_domain(result.separator),
        }
    }
}

/// The resource `random.RandomShuffle` generates a random permutation of a list of strings given as an argument.
///
/// ## Example Usage
///
/// ### Typescript
/// ```typescript
/// import * as pulumi from "@pulumi/pulumi";
/// import * as aws from "@pulumi/aws";
/// import * as random from "@pulumi/random";
///
/// const az = new random.RandomShuffle("az", {
///     inputs: [
///         "us-west-1a",
///         "us-west-1c",
///         "us-west-1d",
///         "us-west-1e",
///     ],
///     resultCount: 2,
/// });
/// const example = new aws.elb.LoadBalancer("example", {availabilityZones: az.results});
/// // ... and other aws_elb arguments ...
/// ```
/// ### Python
/// ```python
/// import pulumi
/// import pulumi_aws as aws
/// import pulumi_random as random
///
/// az = random.RandomShuffle("az",
///     inputs=[
///         "us-west-1a",
///         "us-west-1c",
///         "us-west-1d",
///         "us-west-1e",
///     ],
///     result_count=2)
/// example = aws.elb.LoadBalancer("example", availability_zones=az.results)
/// # ... and other aws_elb arguments ...
/// ```
/// ### C#
/// ```csharp
/// using System.Collections.Generic;
/// using System.Linq;
/// using Pulumi;
/// using Aws = Pulumi.Aws;
/// using Random = Pulumi.Random;
///
/// return await Deployment.RunAsync(() =>
/// {
///     var az = new Random.RandomShuffle("az", new()
///     {
///         Inputs = new[]
///         {
///             "us-west-1a",
///             "us-west-1c",
///             "us-west-1d",
///             "us-west-1e",
///         },
///         ResultCount = 2,
///     });
///
///     var example = new Aws.Elb.LoadBalancer("example", new()
///     {
///         AvailabilityZones = az.Results,
///     });
///
///     // ... and other aws_elb arguments ...
/// });
/// ```
/// ### Go
/// ```go
/// package main
///
/// import (
/// 	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/elb"
/// 	"github.com/pulumi/pulumi-random/sdk/v4/go/random"
/// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
/// )
///
/// func main() {
/// 	pulumi.Run(func(ctx *pulumi.Context) error {
/// 		az, err := random.NewRandomShuffle(ctx, "az", &random.RandomShuffleArgs{
/// 			Inputs: pulumi.StringArray{
/// 				pulumi.String("us-west-1a"),
/// 				pulumi.String("us-west-1c"),
/// 				pulumi.String("us-west-1d"),
/// 				pulumi.String("us-west-1e"),
/// 			},
/// 			ResultCount: pulumi.Int(2),
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		_, err = elb.NewLoadBalancer(ctx, "example", &elb.LoadBalancerArgs{
/// 			AvailabilityZones: az.Results,
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		return nil
/// 	})
/// }
/// ```
/// ### Java
/// ```java
/// package generated_program;
///
/// import com.pulumi.Context;
/// import com.pulumi.Pulumi;
/// import com.pulumi.core.Output;
/// import com.pulumi.random.RandomShuffle;
/// import com.pulumi.random.RandomShuffleArgs;
/// import com.pulumi.aws.elb.LoadBalancer;
/// import com.pulumi.aws.elb.LoadBalancerArgs;
/// import java.util.List;
/// import java.util.ArrayList;
/// import java.util.Map;
/// import java.io.File;
/// import java.nio.file.Files;
/// import java.nio.file.Paths;
///
/// public class App {
///     public static void main(String[] args) {
///         Pulumi.run(App::stack);
///     }
///
///     public static void stack(Context ctx) {
///         var az = new RandomShuffle("az", RandomShuffleArgs.builder()        
///             .inputs(            
///                 "us-west-1a",
///                 "us-west-1c",
///                 "us-west-1d",
///                 "us-west-1e")
///             .resultCount(2)
///             .build());
///
///         var example = new LoadBalancer("example", LoadBalancerArgs.builder()        
///             .availabilityZones(az.results())
///             .build());
///
///     }
/// }
/// ```
/// ### YAML
/// ```yaml
/// resources:
///   az:
///     type: random:RandomShuffle
///     properties:
///       inputs:
///         - us-west-1a
///         - us-west-1c
///         - us-west-1d
///         - us-west-1e
///       resultCount: 2
///   example:
///     type: aws:elb:LoadBalancer
///     properties:
///       # Place the ELB in any two of the given availability zones, selected
///       #   # at random.
///       availabilityZones: ${az.results}
/// ```
pub mod random_shuffle {

    pub struct RandomShuffleArgs {
        /// The list of strings to shuffle.
        pub inputs: pulumi_wasm_rust::Output<Vec<String>>,
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        pub keepers: pulumi_wasm_rust::Output<Option<std::collections::HashMap<String, String>>>,
        /// The number of results to return. Defaults to the number of items in the `input` list. If fewer items are requested, some elements will be excluded from the result. If more items are requested, items will be repeated in the result but not more frequently than the number of items in the input list.
        pub result_count: pulumi_wasm_rust::Output<Option<i32>>,
        /// Arbitrary string with which to seed the random number generator, in order to produce less-volatile permutations of the list.
        pub seed: pulumi_wasm_rust::Output<Option<String>>,
    }

    pub struct RandomShuffleResult {
        /// The list of strings to shuffle.
        pub inputs: pulumi_wasm_rust::Output<Vec<String>>,
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        pub keepers: pulumi_wasm_rust::Output<Option<std::collections::HashMap<String, String>>>,
        /// The number of results to return. Defaults to the number of items in the `input` list. If fewer items are requested, some elements will be excluded from the result. If more items are requested, items will be repeated in the result but not more frequently than the number of items in the input list.
        pub result_count: pulumi_wasm_rust::Output<Option<i32>>,
        /// Random permutation of the list of strings given in `input`.
        pub results: pulumi_wasm_rust::Output<Vec<String>>,
        /// Arbitrary string with which to seed the random number generator, in order to produce less-volatile permutations of the list.
        pub seed: pulumi_wasm_rust::Output<Option<String>>,
    }

    ///
    /// Registers a new resource with the given unique name and arguments
    ///
    pub fn random_shuffle(name: &str, args: RandomShuffleArgs) -> RandomShuffleResult {
        let result = crate::bindings::pulumi::random::random_shuffle::invoke(
            name,
            &crate::bindings::pulumi::random::random_shuffle::Args {
                inputs: args.inputs.get_inner(),
                keepers: args.keepers.get_inner(),
                result_count: args.result_count.get_inner(),
                seed: args.seed.get_inner(),
            },
        );

        RandomShuffleResult {
            inputs: crate::into_domain(result.inputs),
            keepers: crate::into_domain(result.keepers),
            result_count: crate::into_domain(result.result_count),
            results: crate::into_domain(result.results),
            seed: crate::into_domain(result.seed),
        }
    }
}

/// The resource `random.RandomString` generates a random permutation of alphanumeric characters and optionally special characters.
///
/// This resource *does* use a cryptographic random number generator.
///
/// Historically this resource's intended usage has been ambiguous as the original example used it in a password. For backwards compatibility it will continue to exist. For unique ids please use random_id, for sensitive random values please use random_password.
///
/// ## Example Usage
///
/// ### Typescript
/// ```typescript
/// import * as pulumi from "@pulumi/pulumi";
/// import * as random from "@pulumi/random";
///
/// const random = new random.RandomString("random", {
///     length: 16,
///     overrideSpecial: "/@£$",
///     special: true,
/// });
/// ```
/// ### Python
/// ```python
/// import pulumi
/// import pulumi_random as random
///
/// random = random.RandomString("random",
///     length=16,
///     override_special="/@£$",
///     special=True)
/// ```
/// ### C#
/// ```csharp
/// using System.Collections.Generic;
/// using System.Linq;
/// using Pulumi;
/// using Random = Pulumi.Random;
///
/// return await Deployment.RunAsync(() =>
/// {
///     var random = new Random.RandomString("random", new()
///     {
///         Length = 16,
///         OverrideSpecial = "/@£$",
///         Special = true,
///     });
///
/// });
/// ```
/// ### Go
/// ```go
/// package main
///
/// import (
/// 	"github.com/pulumi/pulumi-random/sdk/v4/go/random"
/// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
/// )
///
/// func main() {
/// 	pulumi.Run(func(ctx *pulumi.Context) error {
/// 		_, err := random.NewRandomString(ctx, "random", &random.RandomStringArgs{
/// 			Length:          pulumi.Int(16),
/// 			OverrideSpecial: pulumi.String("/@£$"),
/// 			Special:         pulumi.Bool(true),
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		return nil
/// 	})
/// }
/// ```
/// ### Java
/// ```java
/// package generated_program;
///
/// import com.pulumi.Context;
/// import com.pulumi.Pulumi;
/// import com.pulumi.core.Output;
/// import com.pulumi.random.RandomString;
/// import com.pulumi.random.RandomStringArgs;
/// import java.util.List;
/// import java.util.ArrayList;
/// import java.util.Map;
/// import java.io.File;
/// import java.nio.file.Files;
/// import java.nio.file.Paths;
///
/// public class App {
///     public static void main(String[] args) {
///         Pulumi.run(App::stack);
///     }
///
///     public static void stack(Context ctx) {
///         var random = new RandomString("random", RandomStringArgs.builder()        
///             .length(16)
///             .overrideSpecial("/@£$")
///             .special(true)
///             .build());
///
///     }
/// }
/// ```
/// ### YAML
/// ```yaml
/// resources:
///   random:
///     type: random:RandomString
///     properties:
///       length: 16
///       overrideSpecial: /@£$
///       special: true
/// ```
///
/// ## Import
///
/// You can import external strings into your Pulumi programs as RandomString resources as follows:
///
/// ```sh
///  $ import random:index/randomString:RandomString newString myspecialdata
/// ```
///
/// This command will encode the `myspecialdata` token in Pulumi state and generate a code suggestion to include a new RandomString resource in your Pulumi program. Include the suggested code and do a `pulumi up`. Your data is now stored in Pulumi, and you can reference it in your Pulumi program as `newString.result`.
///
/// If the data needs to be stored securily as a secret, consider using the RandomPassword resource instead.
///
pub mod random_string {

    pub struct RandomStringArgs {
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        pub keepers: pulumi_wasm_rust::Output<Option<std::collections::HashMap<String, String>>>,
        /// The length of the string desired. The minimum value for length is 1 and, length must also be >= (`min_upper` + `min_lower` + `min_numeric` + `min_special`).
        pub length: pulumi_wasm_rust::Output<i32>,
        /// Include lowercase alphabet characters in the result. Default value is `true`.
        pub lower: pulumi_wasm_rust::Output<Option<bool>>,
        /// Minimum number of lowercase alphabet characters in the result. Default value is `0`.
        pub min_lower: pulumi_wasm_rust::Output<Option<i32>>,
        /// Minimum number of numeric characters in the result. Default value is `0`.
        pub min_numeric: pulumi_wasm_rust::Output<Option<i32>>,
        /// Minimum number of special characters in the result. Default value is `0`.
        pub min_special: pulumi_wasm_rust::Output<Option<i32>>,
        /// Minimum number of uppercase alphabet characters in the result. Default value is `0`.
        pub min_upper: pulumi_wasm_rust::Output<Option<i32>>,
        /// Include numeric characters in the result. Default value is `true`. **NOTE**: This is deprecated, use `numeric` instead.
        pub number: pulumi_wasm_rust::Output<Option<bool>>,
        /// Include numeric characters in the result. Default value is `true`.
        pub numeric: pulumi_wasm_rust::Output<Option<bool>>,
        /// Supply your own list of special characters to use for string generation.  This overrides the default character list in the special argument.  The `special` argument must still be set to true for any overwritten characters to be used in generation.
        pub override_special: pulumi_wasm_rust::Output<Option<String>>,
        /// Include special characters in the result. These are `!@#$%&*()-_=+[]{}<>:?`. Default value is `true`.
        pub special: pulumi_wasm_rust::Output<Option<bool>>,
        /// Include uppercase alphabet characters in the result. Default value is `true`.
        pub upper: pulumi_wasm_rust::Output<Option<bool>>,
    }

    pub struct RandomStringResult {
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        pub keepers: pulumi_wasm_rust::Output<Option<std::collections::HashMap<String, String>>>,
        /// The length of the string desired. The minimum value for length is 1 and, length must also be >= (`min_upper` + `min_lower` + `min_numeric` + `min_special`).
        pub length: pulumi_wasm_rust::Output<i32>,
        /// Include lowercase alphabet characters in the result. Default value is `true`.
        pub lower: pulumi_wasm_rust::Output<bool>,
        /// Minimum number of lowercase alphabet characters in the result. Default value is `0`.
        pub min_lower: pulumi_wasm_rust::Output<i32>,
        /// Minimum number of numeric characters in the result. Default value is `0`.
        pub min_numeric: pulumi_wasm_rust::Output<i32>,
        /// Minimum number of special characters in the result. Default value is `0`.
        pub min_special: pulumi_wasm_rust::Output<i32>,
        /// Minimum number of uppercase alphabet characters in the result. Default value is `0`.
        pub min_upper: pulumi_wasm_rust::Output<i32>,
        /// Include numeric characters in the result. Default value is `true`. **NOTE**: This is deprecated, use `numeric` instead.
        pub number: pulumi_wasm_rust::Output<bool>,
        /// Include numeric characters in the result. Default value is `true`.
        pub numeric: pulumi_wasm_rust::Output<bool>,
        /// Supply your own list of special characters to use for string generation.  This overrides the default character list in the special argument.  The `special` argument must still be set to true for any overwritten characters to be used in generation.
        pub override_special: pulumi_wasm_rust::Output<Option<String>>,
        /// The generated random string.
        pub result: pulumi_wasm_rust::Output<String>,
        /// Include special characters in the result. These are `!@#$%&*()-_=+[]{}<>:?`. Default value is `true`.
        pub special: pulumi_wasm_rust::Output<bool>,
        /// Include uppercase alphabet characters in the result. Default value is `true`.
        pub upper: pulumi_wasm_rust::Output<bool>,
    }

    ///
    /// Registers a new resource with the given unique name and arguments
    ///
    pub fn random_string(name: &str, args: RandomStringArgs) -> RandomStringResult {
        let result = crate::bindings::pulumi::random::random_string::invoke(
            name,
            &crate::bindings::pulumi::random::random_string::Args {
                keepers: args.keepers.get_inner(),
                length: args.length.get_inner(),
                lower: args.lower.get_inner(),
                min_lower: args.min_lower.get_inner(),
                min_numeric: args.min_numeric.get_inner(),
                min_special: args.min_special.get_inner(),
                min_upper: args.min_upper.get_inner(),
                number: args.number.get_inner(),
                numeric: args.numeric.get_inner(),
                override_special: args.override_special.get_inner(),
                special: args.special.get_inner(),
                upper: args.upper.get_inner(),
            },
        );

        RandomStringResult {
            keepers: crate::into_domain(result.keepers),
            length: crate::into_domain(result.length),
            lower: crate::into_domain(result.lower),
            min_lower: crate::into_domain(result.min_lower),
            min_numeric: crate::into_domain(result.min_numeric),
            min_special: crate::into_domain(result.min_special),
            min_upper: crate::into_domain(result.min_upper),
            number: crate::into_domain(result.number),
            numeric: crate::into_domain(result.numeric),
            override_special: crate::into_domain(result.override_special),
            result: crate::into_domain(result.result),
            special: crate::into_domain(result.special),
            upper: crate::into_domain(result.upper),
        }
    }
}

/// The resource `random.RandomUuid` generates a random uuid string that is intended to be used as a unique identifier for other resources.
///
/// This resource uses [hashicorp/go-uuid](https://github.com/hashicorp/go-uuid) to generate a UUID-formatted string for use with services needing a unique string identifier.
///
/// ## Example Usage
///
/// ### Typescript
/// ```typescript
/// import * as pulumi from "@pulumi/pulumi";
/// import * as azure from "@pulumi/azure";
/// import * as random from "@pulumi/random";
///
/// const testRandomUuid = new random.RandomUuid("testRandomUuid", {});
/// const testResourceGroup = new azure.core.ResourceGroup("testResourceGroup", {location: "Central US"});
/// ```
/// ### Python
/// ```python
/// import pulumi
/// import pulumi_azure as azure
/// import pulumi_random as random
///
/// test_random_uuid = random.RandomUuid("testRandomUuid")
/// test_resource_group = azure.core.ResourceGroup("testResourceGroup", location="Central US")
/// ```
/// ### C#
/// ```csharp
/// using System.Collections.Generic;
/// using System.Linq;
/// using Pulumi;
/// using Azure = Pulumi.Azure;
/// using Random = Pulumi.Random;
///
/// return await Deployment.RunAsync(() =>
/// {
///     var testRandomUuid = new Random.RandomUuid("testRandomUuid");
///
///     var testResourceGroup = new Azure.Core.ResourceGroup("testResourceGroup", new()
///     {
///         Location = "Central US",
///     });
///
/// });
/// ```
/// ### Go
/// ```go
/// package main
///
/// import (
/// 	"github.com/pulumi/pulumi-azure/sdk/v5/go/azure/core"
/// 	"github.com/pulumi/pulumi-random/sdk/v4/go/random"
/// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
/// )
///
/// func main() {
/// 	pulumi.Run(func(ctx *pulumi.Context) error {
/// 		_, err := random.NewRandomUuid(ctx, "testRandomUuid", nil)
/// 		if err != nil {
/// 			return err
/// 		}
/// 		_, err = core.NewResourceGroup(ctx, "testResourceGroup", &core.ResourceGroupArgs{
/// 			Location: pulumi.String("Central US"),
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		return nil
/// 	})
/// }
/// ```
/// ### Java
/// ```java
/// package generated_program;
///
/// import com.pulumi.Context;
/// import com.pulumi.Pulumi;
/// import com.pulumi.core.Output;
/// import com.pulumi.random.RandomUuid;
/// import com.pulumi.azure.core.ResourceGroup;
/// import com.pulumi.azure.core.ResourceGroupArgs;
/// import java.util.List;
/// import java.util.ArrayList;
/// import java.util.Map;
/// import java.io.File;
/// import java.nio.file.Files;
/// import java.nio.file.Paths;
///
/// public class App {
///     public static void main(String[] args) {
///         Pulumi.run(App::stack);
///     }
///
///     public static void stack(Context ctx) {
///         var testRandomUuid = new RandomUuid("testRandomUuid");
///
///         var testResourceGroup = new ResourceGroup("testResourceGroup", ResourceGroupArgs.builder()        
///             .location("Central US")
///             .build());
///
///     }
/// }
/// ```
/// ### YAML
/// ```yaml
/// resources:
///   testRandomUuid:
///     type: random:RandomUuid
///   testResourceGroup:
///     type: azure:core:ResourceGroup
///     properties:
///       location: Central US
/// ```
///
/// ## Import
///
/// Random UUID's can be imported. This can be used to replace a config value with a value interpolated from the random provider without experiencing diffs.
///
/// ```sh
///  $ pulumi import random:index/randomUuid:RandomUuid main aabbccdd-eeff-0011-2233-445566778899
/// ```
///
///  
pub mod random_uuid {

    pub struct RandomUuidArgs {
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        pub keepers: pulumi_wasm_rust::Output<Option<std::collections::HashMap<String, String>>>,
    }

    pub struct RandomUuidResult {
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        pub keepers: pulumi_wasm_rust::Output<Option<std::collections::HashMap<String, String>>>,
        /// The generated uuid presented in string format.
        pub result: pulumi_wasm_rust::Output<String>,
    }

    ///
    /// Registers a new resource with the given unique name and arguments
    ///
    pub fn random_uuid(name: &str, args: RandomUuidArgs) -> RandomUuidResult {
        let result = crate::bindings::pulumi::random::random_uuid::invoke(
            name,
            &crate::bindings::pulumi::random::random_uuid::Args {
                keepers: args.keepers.get_inner(),
            },
        );

        RandomUuidResult {
            keepers: crate::into_domain(result.keepers),
            result: crate::into_domain(result.result),
        }
    }
}
