set windows-shell := ["pwsh.exe", "-c"]

[windows]
run $RUST_BACKTRACE="1":
    New-Item -ItemType Directory -Path build -Force
    cd build && cmake .. && cmake --build .
    .\build\Debug\PulumiNativeC.exe

[unix]
run $RUST_BACKTRACE="1":
    mkdir -p build
    cd build && cmake .. && cmake --build .
    ./build/PulumiNativeC

[windows]
local-test:
    #!pwsh
    Set-StrictMode -Version Latest
    $ErrorActionPreference = "Stop"
    $PSNativeCommandUseErrorActionPreference = $true

    cargo build -p pulumi_native_c
    $env:PULUMI_CONFIG_PASSPHRASE=" "
    pulumi destroy -y
    pulumi up -y