set windows-shell := ["pwsh.exe", "-c"]
binary := "../../target/release/pulumi_wasm_runner"
wasm := "../../target/wasm32-wasip2/release/pulumi_wasm_example_multiple_providers.wasm"
pulumi_wasm := "../../target/wasm32-wasip2/release/pulumi_wasm.wasm"
docker := "../../target/wasm32-wasip2/release/pulumi_wasm_docker_provider.wasm"
random := "../../target/wasm32-wasip2/release/pulumi_wasm_random_provider.wasm"
TARGET_NAME := "wasm32-wasip2"

run:
    {{binary}} run --pulumi-wasm "{{pulumi_wasm}}" --provider "docker={{docker}}" --provider "random={{random}}" "{{wasm}}"

[windows]
local-test:
    #!pwsh
    Set-StrictMode -Version Latest
    $ErrorActionPreference = "Stop"
    $PSNativeCommandUseErrorActionPreference = $true

    cargo build -p pulumi_wasm_runner --release
    cargo build -p pulumi_wasm --release --target={{TARGET_NAME}}
    cargo build -p pulumi_wasm_example_multiple_providers --release --target={{TARGET_NAME}}
    cargo build -p pulumi_wasm_docker_provider --release --target={{TARGET_NAME}}
    cargo build -p pulumi_wasm_random_provider --release --target={{TARGET_NAME}}
    $env:PULUMI_CONFIG_PASSPHRASE=" "
    pulumi destroy -y
    pulumi up -y