set windows-shell := ["pwsh.exe", "-c"]
binary := "../../target/release/pulumi_wasm_runner"
wasm := "../../target/wasm32-wasip1/release/pulumi_wasm_example_multiple_providers.wasm"
pulumi_wasm := "../../target/wasm32-wasip1/release/pulumi_wasm.wasm"

run:
    {{binary}} run --pulumi-wasm "{{pulumi_wasm}}" "{{wasm}}"

[windows]
local-test:
    #!pwsh
    Set-StrictMode -Version Latest
    $ErrorActionPreference = "Stop"
    $PSNativeCommandUseErrorActionPreference = $true

    cargo build -p pulumi_wasm_runner --release
    cargo component build -p pulumi_wasm --release
    cargo component build -p pulumi_wasm_example_multiple_providers --release
    $env:PULUMI_CONFIG_PASSPHRASE=" "
    pulumi destroy -y
    pulumi up -y