package component:pulumi-gestalt@0.0.0-DEV;

world pulumi-gestalt {
    export output-interface;
    export types;
    export context;

    import component:pulumi-gestalt-external/log@0.0.0-STABLE-DEV;
    import component:pulumi-gestalt-external/external-world@0.0.0-STABLE-DEV;
}

world client {
    import output-interface;
    import types;
    import context;
    export component:pulumi-gestalt-external/pulumi-main@0.0.0-STABLE-DEV; // Used by macro
}

world logger {
    import component:pulumi-gestalt-external/log@0.0.0-STABLE-DEV;
}

world runner {
    export component:pulumi-gestalt-external/pulumi-main@0.0.0-STABLE-DEV;
    import component:pulumi-gestalt-external/external-world@0.0.0-STABLE-DEV;
    import component:pulumi-gestalt-external/log@0.0.0-STABLE-DEV;
}


interface output-interface {

    resource output {
        map: func(function-name: string) -> output;
        clone: func() -> output;
        combine: func(outputs: list<borrow<output>>) -> output;
        add-to-export: func(name: string);
    }

    resource composite-output {
        extract-field: func(field-name: string) -> output;
    }
}

interface types {
    use output-interface.{output};

    record function-invocation-request {
        id: output,
        function-id: string,
        value: string,
    }
    record function-invocation-result {
        id: borrow<output>,
        value: string,
    }
    
    record object-field {
        name: string,
        value: borrow<output>
    }

    record register-resource-request {
        %type: string,
        name: string,
        version: string,
        object: list<object-field>,
    }


    record resource-invoke-request {
        token: string,
        version: string,
        object: list<object-field>,
    }
    
}

interface context {
    use output-interface.{output, composite-output};
    use types.{register-resource-request, resource-invoke-request, function-invocation-result, function-invocation-request};

    resource context {
        constructor(in-preview: bool);
        create-output: func(value: string, secret:bool) -> output;
        register-resource: func(request: register-resource-request) -> composite-output;
        invoke-resource: func(request: resource-invoke-request) -> composite-output;
        finish: func(functions: list<function-invocation-result>) -> list<function-invocation-request>;
    }
}
