package component:pulumi-gestalt@0.0.0-test11;

world pulumi-gestalt {
    export output-interface;
    export register-interface;
    export stack-interface;
    export pulumi-engine;

    import component:pulumi-gestalt-external/log@0.0.0-STABLE-DEV;
    import component:pulumi-gestalt-external/external-world@0.0.0-STABLE-DEV;
}

world client {
    import output-interface;
    import stack-interface;
    import register-interface;
    import pulumi-engine;
    export component:pulumi-gestalt-external/pulumi-main@0.0.0-STABLE-DEV; // Used by macro
}

world logger {
    import component:pulumi-gestalt-external/log@0.0.0-STABLE-DEV;
}

world runner {
    export component:pulumi-gestalt-external/pulumi-main@0.0.0-STABLE-DEV;
    import component:pulumi-gestalt-external/external-world@0.0.0-STABLE-DEV;
    import component:pulumi-gestalt-external/log@0.0.0-STABLE-DEV;
}

interface pulumi-engine {
    resource engine {
        constructor(in-preview: bool);
    }
}

interface output-interface {
    use pulumi-engine.{engine};

    resource output {
        constructor(engine: borrow<engine>, value: string, secret: bool);
        map: func(function-name: string) -> output;
        clone: func() -> output;
    }
    combine: func(outputs: list<borrow<output>>) -> output;

    resource register-output {
        extract-field: func(field-name: string) -> output;
    }
}

interface stack-interface {
    use pulumi-engine.{engine};
    use output-interface.{output};

    record function-invocation-request {
        id: output,
        function-id: string,
        value: string,
    }
    record function-invocation-result {
        id: borrow<output>,
        value: string,
    }
    add-export: func(name: string, value: borrow<output>);
    finish: func(engine: borrow<engine>, functions: list<function-invocation-result>) -> list<function-invocation-request>;
}

interface register-interface {
    use pulumi-engine.{engine};
    use output-interface.{output, register-output};

    record object-field {
        name: string,
        value: borrow<output>
    }

    record register-resource-request {
        %type: string,
        name: string,
        version: string,
        object: list<object-field>,
    }

    register: func(engine: borrow<engine>, request: register-resource-request) -> register-output;

    record resource-invoke-request {
        token: string,
        version: string,
        object: list<object-field>,
    }

    invoke: func(engine: borrow<engine>, request: resource-invoke-request) -> register-output;
}
