#[derive(serde::Deserialize, serde::Serialize, Debug)]
pub struct AccessIdentityProviderConfig {
    #[serde(rename = "apiToken")]
    pub r#api_token: Box<Option<String>>,
    #[serde(rename = "appsDomain")]
    pub r#apps_domain: Box<Option<String>>,
    #[serde(rename = "attributes")]
    pub r#attributes: Box<Option<Vec<String>>>,
    #[serde(rename = "authUrl")]
    pub r#auth_url: Box<Option<String>>,
    #[serde(rename = "authorizationServerId")]
    pub r#authorization_server_id: Box<Option<String>>,
    #[serde(rename = "centrifyAccount")]
    pub r#centrify_account: Box<Option<String>>,
    #[serde(rename = "centrifyAppId")]
    pub r#centrify_app_id: Box<Option<String>>,
    #[serde(rename = "certsUrl")]
    pub r#certs_url: Box<Option<String>>,
    #[serde(rename = "claims")]
    pub r#claims: Box<Option<Vec<String>>>,
    #[serde(rename = "clientId")]
    pub r#client_id: Box<Option<String>>,
    #[serde(rename = "clientSecret")]
    pub r#client_secret: Box<Option<String>>,
    #[serde(rename = "conditionalAccessEnabled")]
    pub r#conditional_access_enabled: Box<Option<bool>>,
    #[serde(rename = "directoryId")]
    pub r#directory_id: Box<Option<String>>,
    #[serde(rename = "emailAttributeName")]
    pub r#email_attribute_name: Box<Option<String>>,
    #[serde(rename = "emailClaimName")]
    pub r#email_claim_name: Box<Option<String>>,
    #[serde(rename = "idpPublicCert")]
    pub r#idp_public_cert: Box<Option<String>>,
    #[serde(rename = "issuerUrl")]
    pub r#issuer_url: Box<Option<String>>,
    #[serde(rename = "oktaAccount")]
    pub r#okta_account: Box<Option<String>>,
    #[serde(rename = "oneloginAccount")]
    pub r#onelogin_account: Box<Option<String>>,
    #[serde(rename = "pingEnvId")]
    pub r#ping_env_id: Box<Option<String>>,
    #[serde(rename = "pkceEnabled")]
    pub r#pkce_enabled: Box<Option<bool>>,
    #[serde(rename = "redirectUrl")]
    pub r#redirect_url: Box<Option<String>>,
    #[serde(rename = "scopes")]
    pub r#scopes: Box<Option<Vec<String>>>,
    #[serde(rename = "signRequest")]
    pub r#sign_request: Box<Option<bool>>,
    #[serde(rename = "ssoTargetUrl")]
    pub r#sso_target_url: Box<Option<String>>,
    #[serde(rename = "supportGroups")]
    pub r#support_groups: Box<Option<bool>>,
    #[serde(rename = "tokenUrl")]
    pub r#token_url: Box<Option<String>>,
}
