#[derive(serde::Serialize)]
pub struct DevicePostureRuleInput {
    #[serde(rename = "activeThreats")]
    pub r#active_threats: Box<Option<i32>>,
    #[serde(rename = "certificateId")]
    pub r#certificate_id: Box<Option<String>>,
    #[serde(rename = "checkDisks")]
    pub r#check_disks: Box<Option<Vec<String>>>,
    #[serde(rename = "cn")]
    pub r#cn: Box<Option<String>>,
    #[serde(rename = "complianceStatus")]
    pub r#compliance_status: Box<Option<String>>,
    #[serde(rename = "connectionId")]
    pub r#connection_id: Box<Option<String>>,
    #[serde(rename = "countOperator")]
    pub r#count_operator: Box<Option<String>>,
    #[serde(rename = "domain")]
    pub r#domain: Box<Option<String>>,
    #[serde(rename = "eidLastSeen")]
    pub r#eid_last_seen: Box<Option<String>>,
    #[serde(rename = "enabled")]
    pub r#enabled: Box<Option<bool>>,
    #[serde(rename = "exists")]
    pub r#exists: Box<Option<bool>>,
    #[serde(rename = "id")]
    pub r#id: Box<Option<String>>,
    #[serde(rename = "infected")]
    pub r#infected: Box<Option<bool>>,
    #[serde(rename = "isActive")]
    pub r#is_active: Box<Option<bool>>,
    #[serde(rename = "issueCount")]
    pub r#issue_count: Box<Option<String>>,
    #[serde(rename = "lastSeen")]
    pub r#last_seen: Box<Option<String>>,
    #[serde(rename = "networkStatus")]
    pub r#network_status: Box<Option<String>>,
    #[serde(rename = "operator")]
    pub r#operator: Box<Option<String>>,
    #[serde(rename = "os")]
    pub r#os: Box<Option<String>>,
    #[serde(rename = "osDistroName")]
    pub r#os_distro_name: Box<Option<String>>,
    #[serde(rename = "osDistroRevision")]
    pub r#os_distro_revision: Box<Option<String>>,
    #[serde(rename = "overall")]
    pub r#overall: Box<Option<String>>,
    #[serde(rename = "path")]
    pub r#path: Box<Option<String>>,
    #[serde(rename = "requireAll")]
    pub r#require_all: Box<Option<bool>>,
    #[serde(rename = "riskLevel")]
    pub r#risk_level: Box<Option<String>>,
    #[serde(rename = "running")]
    pub r#running: Box<Option<bool>>,
    #[serde(rename = "sensorConfig")]
    pub r#sensor_config: Box<Option<String>>,
    #[serde(rename = "sha256")]
    pub r#sha_256: Box<Option<String>>,
    #[serde(rename = "state")]
    pub r#state: Box<Option<String>>,
    #[serde(rename = "thumbprint")]
    pub r#thumbprint: Box<Option<String>>,
    #[serde(rename = "totalScore")]
    pub r#total_score: Box<Option<i32>>,
    #[serde(rename = "version")]
    pub r#version: Box<Option<String>>,
    #[serde(rename = "versionOperator")]
    pub r#version_operator: Box<Option<String>>,
}
