#[derive(serde::Serialize)]
pub struct GetRulesetsRulesetRuleActionParameters {
    #[serde(rename = "additionalCacheablePorts")]
    pub r#additional_cacheable_ports: Box<Option<Vec<i32>>>,
    #[serde(rename = "automaticHttpsRewrites")]
    pub r#automatic_https_rewrites: Box<Option<bool>>,
    #[serde(rename = "autominifies")]
    pub r#autominifies:
        Box<Option<Vec<crate::types::GetRulesetsRulesetRuleActionParametersAutominify>>>,
    #[serde(rename = "bic")]
    pub r#bic: Box<Option<bool>>,
    #[serde(rename = "browserTtl")]
    pub r#browser_ttl: Box<Option<crate::types::GetRulesetsRulesetRuleActionParametersBrowserTtl>>,
    #[serde(rename = "cache")]
    pub r#cache: Box<Option<bool>>,
    #[serde(rename = "cacheKey")]
    pub r#cache_key: Box<Option<crate::types::GetRulesetsRulesetRuleActionParametersCacheKey>>,
    #[serde(rename = "content")]
    pub r#content: Box<Option<String>>,
    #[serde(rename = "contentType")]
    pub r#content_type: Box<Option<String>>,
    #[serde(rename = "cookieFields")]
    pub r#cookie_fields: Box<Option<Vec<String>>>,
    #[serde(rename = "disableApps")]
    pub r#disable_apps: Box<Option<bool>>,
    #[serde(rename = "disableRailgun")]
    pub r#disable_railgun: Box<Option<bool>>,
    #[serde(rename = "disableZaraz")]
    pub r#disable_zaraz: Box<Option<bool>>,
    #[serde(rename = "edgeTtl")]
    pub r#edge_ttl: Box<Option<crate::types::GetRulesetsRulesetRuleActionParametersEdgeTtl>>,
    #[serde(rename = "emailObfuscation")]
    pub r#email_obfuscation: Box<Option<bool>>,
    #[serde(rename = "fromList")]
    pub r#from_list: Box<Option<crate::types::GetRulesetsRulesetRuleActionParametersFromList>>,
    #[serde(rename = "fromValue")]
    pub r#from_value: Box<Option<crate::types::GetRulesetsRulesetRuleActionParametersFromValue>>,
    #[serde(rename = "headers")]
    pub r#headers: Box<Option<Vec<crate::types::GetRulesetsRulesetRuleActionParametersHeader>>>,
    #[serde(rename = "hostHeader")]
    pub r#host_header: Box<Option<String>>,
    #[serde(rename = "hotlinkProtection")]
    pub r#hotlink_protection: Box<Option<bool>>,
    #[serde(rename = "id")]
    pub r#id: Box<Option<String>>,
    #[serde(rename = "increment")]
    pub r#increment: Box<Option<i32>>,
    #[serde(rename = "matchedData")]
    pub r#matched_data:
        Box<Option<crate::types::GetRulesetsRulesetRuleActionParametersMatchedData>>,
    #[serde(rename = "mirage")]
    pub r#mirage: Box<Option<bool>>,
    #[serde(rename = "opportunisticEncryption")]
    pub r#opportunistic_encryption: Box<Option<bool>>,
    #[serde(rename = "origin")]
    pub r#origin: Box<Option<crate::types::GetRulesetsRulesetRuleActionParametersOrigin>>,
    #[serde(rename = "originCacheControl")]
    pub r#origin_cache_control: Box<Option<bool>>,
    #[serde(rename = "originErrorPagePassthru")]
    pub r#origin_error_page_passthru: Box<Option<bool>>,
    #[serde(rename = "overrides")]
    pub r#overrides: Box<Option<crate::types::GetRulesetsRulesetRuleActionParametersOverrides>>,
    #[serde(rename = "phases")]
    pub r#phases: Box<Option<Vec<String>>>,
    #[serde(rename = "polish")]
    pub r#polish: Box<Option<String>>,
    #[serde(rename = "products")]
    pub r#products: Box<Option<Vec<String>>>,
    #[serde(rename = "readTimeout")]
    pub r#read_timeout: Box<Option<i32>>,
    #[serde(rename = "requestFields")]
    pub r#request_fields: Box<Option<Vec<String>>>,
    #[serde(rename = "respectStrongEtags")]
    pub r#respect_strong_etags: Box<Option<bool>>,
    #[serde(rename = "responseFields")]
    pub r#response_fields: Box<Option<Vec<String>>>,
    #[serde(rename = "responses")]
    pub r#responses: Box<Option<Vec<crate::types::GetRulesetsRulesetRuleActionParametersResponse>>>,
    #[serde(rename = "rocketLoader")]
    pub r#rocket_loader: Box<Option<bool>>,
    #[serde(rename = "rules")]
    pub r#rules: Box<Option<std::collections::HashMap<String, String>>>,
    #[serde(rename = "ruleset")]
    pub r#ruleset: Box<Option<String>>,
    #[serde(rename = "rulesets")]
    pub r#rulesets: Box<Option<Vec<String>>>,
    #[serde(rename = "securityLevel")]
    pub r#security_level: Box<Option<String>>,
    #[serde(rename = "serveStale")]
    pub r#serve_stale: Box<Option<crate::types::GetRulesetsRulesetRuleActionParametersServeStale>>,
    #[serde(rename = "serverSideExcludes")]
    pub r#server_side_excludes: Box<Option<bool>>,
    #[serde(rename = "sni")]
    pub r#sni: Box<Option<crate::types::GetRulesetsRulesetRuleActionParametersSni>>,
    #[serde(rename = "ssl")]
    pub r#ssl: Box<Option<String>>,
    #[serde(rename = "statusCode")]
    pub r#status_code: Box<Option<i32>>,
    #[serde(rename = "sxg")]
    pub r#sxg: Box<Option<bool>>,
    #[serde(rename = "uri")]
    pub r#uri: Box<Option<crate::types::GetRulesetsRulesetRuleActionParametersUri>>,
    #[serde(rename = "version")]
    pub r#version: Box<String>,
}
