#[derive(serde::Serialize)]
pub struct NotificationPolicyFilters {
    #[serde(rename = "actions")]
    pub r#actions: Box<Option<Vec<String>>>,
    #[serde(rename = "affectedComponents")]
    pub r#affected_components: Box<Option<Vec<String>>>,
    #[serde(rename = "airportCodes")]
    pub r#airport_codes: Box<Option<Vec<String>>>,
    #[serde(rename = "alertTriggerPreferences")]
    pub r#alert_trigger_preferences: Box<Option<Vec<String>>>,
    #[serde(rename = "enableds")]
    pub r#enableds: Box<Option<Vec<String>>>,
    #[serde(rename = "environments")]
    pub r#environments: Box<Option<Vec<String>>>,
    #[serde(rename = "eventSources")]
    pub r#event_sources: Box<Option<Vec<String>>>,
    #[serde(rename = "eventTypes")]
    pub r#event_types: Box<Option<Vec<String>>>,
    #[serde(rename = "events")]
    pub r#events: Box<Option<Vec<String>>>,
    #[serde(rename = "groupBies")]
    pub r#group_bies: Box<Option<Vec<String>>>,
    #[serde(rename = "healthCheckIds")]
    pub r#health_check_ids: Box<Option<Vec<String>>>,
    #[serde(rename = "incidentImpacts")]
    pub r#incident_impacts: Box<Option<Vec<String>>>,
    #[serde(rename = "inputIds")]
    pub r#input_ids: Box<Option<Vec<String>>>,
    #[serde(rename = "limits")]
    pub r#limits: Box<Option<Vec<String>>>,
    #[serde(rename = "megabitsPerSeconds")]
    pub r#megabits_per_seconds: Box<Option<Vec<String>>>,
    #[serde(rename = "newHealths")]
    pub r#new_healths: Box<Option<Vec<String>>>,
    #[serde(rename = "newStatuses")]
    pub r#new_statuses: Box<Option<Vec<String>>>,
    #[serde(rename = "packetsPerSeconds")]
    pub r#packets_per_seconds: Box<Option<Vec<String>>>,
    #[serde(rename = "poolIds")]
    pub r#pool_ids: Box<Option<Vec<String>>>,
    #[serde(rename = "products")]
    pub r#products: Box<Option<Vec<String>>>,
    #[serde(rename = "projectIds")]
    pub r#project_ids: Box<Option<Vec<String>>>,
    #[serde(rename = "protocols")]
    pub r#protocols: Box<Option<Vec<String>>>,
    #[serde(rename = "requestsPerSeconds")]
    pub r#requests_per_seconds: Box<Option<Vec<String>>>,
    #[serde(rename = "selectors")]
    pub r#selectors: Box<Option<Vec<String>>>,
    #[serde(rename = "services")]
    pub r#services: Box<Option<Vec<String>>>,
    #[serde(rename = "slos")]
    pub r#slos: Box<Option<Vec<String>>>,
    #[serde(rename = "statuses")]
    pub r#statuses: Box<Option<Vec<String>>>,
    #[serde(rename = "targetHostnames")]
    pub r#target_hostnames: Box<Option<Vec<String>>>,
    #[serde(rename = "targetZoneNames")]
    pub r#target_zone_names: Box<Option<Vec<String>>>,
    #[serde(rename = "tunnelIds")]
    pub r#tunnel_ids: Box<Option<Vec<String>>>,
    #[serde(rename = "wheres")]
    pub r#wheres: Box<Option<Vec<String>>>,
    #[serde(rename = "zones")]
    pub r#zones: Box<Option<Vec<String>>>,
}
