set windows-shell := ["pwsh.exe", "-c"]
binary := "../../target/release/pulumi_gestalt_runner"
wasm := "../../target/wasm32-wasip1/release/pulumi_gestalt_example_secret.wasm"
pulumi_gestalt := "../../target/wasm32-wasip1/release/pulumi_gestalt.wasm"

run:
    {{binary}} run --pulumi-gestalt "{{pulumi_gestalt}}" "{{wasm}}"

plugins TEMP_FILE:
    {{binary}} plugins "{{wasm}}" "{{TEMP_FILE}}"

[windows]
local-test:
    #!pwsh
    Set-StrictMode -Version Latest
    $ErrorActionPreference = "Stop"
    $PSNativeCommandUseErrorActionPreference = $true

    cargo build -p pulumi_gestalt_runner --release
    cargo component build -p pulumi_gestalt --release
    cargo component build -p pulumi_gestalt_example_secret --release
    $env:PULUMI_CONFIG_PASSPHRASE=" "
    pulumi destroy -y
    pulumi up -y