set windows-shell := ["pwsh.exe", "-c"]
binary := "../../target/release/pulumi_gestalt_wasm_runner"
wasm := "../../target/wasm32-wasip2/release/pulumi_gestalt_example_secret.wasm"
pulumi_gestalt := "../../target/wasm32-wasip2/release/pulumi_gestalt.wasm"
wasi_target_name := "wasm32-wasip2"

run:
    {{binary}} run --pulumi-gestalt "{{pulumi_gestalt}}" "{{wasm}}"

plugins TEMP_FILE:
    {{binary}} plugins "{{wasm}}" "{{TEMP_FILE}}"

[windows]
local-test:
    #!pwsh
    Set-StrictMode -Version Latest
    $ErrorActionPreference = "Stop"
    $PSNativeCommandUseErrorActionPreference = $true

    cargo build -p pulumi_gestalt_wasm_runner --release
    cargo build -p pulumi_gestalt --release --target={{wasi_target_name}}
    cargo build -p pulumi_gestalt_example_secret --release --target={{wasi_target_name}}
    $env:PULUMI_CONFIG_PASSPHRASE=" "
    pulumi destroy -y
    pulumi up -y