set windows-shell := ["pwsh.exe", "-c"]

run:
    New-Item -ItemType Directory -Path build -Force
    cd build && cmake .. && cmake --build .
    .\build\Debug\PulumiNativeCPP.exe

[windows]
local-test:
    #!pwsh
    Set-StrictMode -Version Latest
    $ErrorActionPreference = "Stop"
    $PSNativeCommandUseErrorActionPreference = $true

    cargo build -p pulumi_wasm_runner --release
    cargo component build -p pulumi_wasm --release
    cargo component build -p pulumi_wasm_example_simple --release
    $env:PULUMI_CONFIG_PASSPHRASE=" "
    pulumi destroy -y
    pulumi up -y