mod integer_enum;
pub use integer_enum::*;
mod my_enum;
pub use my_enum::*;
mod number_enum;
pub use number_enum::*;
mod union_case_1;
pub use union_case_1::*;
mod union_case_2;
pub use union_case_2::*;
mod union_case_with_const_1;
pub use union_case_with_const_1::*;
mod union_case_with_const_2;
pub use union_case_with_const_2::*;
