pub struct DeviceSettingsPolicyArgs {
    pub account_id: pulumi_wasm_rust::Output<String>,
    pub allow_mode_switch: pulumi_wasm_rust::Output<Option<bool>>,
    pub allow_updates: pulumi_wasm_rust::Output<Option<bool>>,
    pub allowed_to_leave: pulumi_wasm_rust::Output<Option<bool>>,
    pub auto_connect: pulumi_wasm_rust::Output<Option<i32>>,
    pub captive_portal: pulumi_wasm_rust::Output<Option<i32>>,
    pub default: pulumi_wasm_rust::Output<Option<bool>>,
    pub description: pulumi_wasm_rust::Output<String>,
    pub disable_auto_fallback: pulumi_wasm_rust::Output<Option<bool>>,
    pub enabled: pulumi_wasm_rust::Output<Option<bool>>,
    pub exclude_office_ips: pulumi_wasm_rust::Output<Option<bool>>,
    pub match_: pulumi_wasm_rust::Output<Option<String>>,
    pub name: pulumi_wasm_rust::Output<String>,
    pub precedence: pulumi_wasm_rust::Output<Option<i32>>,
    pub service_mode_v2_mode: pulumi_wasm_rust::Output<Option<String>>,
    pub service_mode_v2_port: pulumi_wasm_rust::Output<Option<i32>>,
    pub support_url: pulumi_wasm_rust::Output<Option<String>>,
    pub switch_locked: pulumi_wasm_rust::Output<Option<bool>>,
}

pub struct DeviceSettingsPolicyResult {
    pub account_id: pulumi_wasm_rust::Output<String>,
    pub allow_mode_switch: pulumi_wasm_rust::Output<Option<bool>>,
    pub allow_updates: pulumi_wasm_rust::Output<Option<bool>>,
    pub allowed_to_leave: pulumi_wasm_rust::Output<Option<bool>>,
    pub auto_connect: pulumi_wasm_rust::Output<Option<i32>>,
    pub captive_portal: pulumi_wasm_rust::Output<Option<i32>>,
    pub default: pulumi_wasm_rust::Output<Option<bool>>,
    pub description: pulumi_wasm_rust::Output<String>,
    pub disable_auto_fallback: pulumi_wasm_rust::Output<Option<bool>>,
    pub enabled: pulumi_wasm_rust::Output<Option<bool>>,
    pub exclude_office_ips: pulumi_wasm_rust::Output<Option<bool>>,
    pub match_: pulumi_wasm_rust::Output<Option<String>>,
    pub name: pulumi_wasm_rust::Output<String>,
    pub precedence: pulumi_wasm_rust::Output<Option<i32>>,
    pub service_mode_v2_mode: pulumi_wasm_rust::Output<Option<String>>,
    pub service_mode_v2_port: pulumi_wasm_rust::Output<Option<i32>>,
    pub support_url: pulumi_wasm_rust::Output<Option<String>>,
    pub switch_locked: pulumi_wasm_rust::Output<Option<bool>>,
}

pub fn create(name: &str, args: DeviceSettingsPolicyArgs) -> DeviceSettingsPolicyResult {
    let result = crate::bindings::pulumi::cloudflare::device_settings_policy::invoke(
        name,
        &crate::bindings::pulumi::cloudflare::device_settings_policy::Args {
            account_id: args.account_id.get_inner(),
            allow_mode_switch: args.allow_mode_switch.get_inner(),
            allow_updates: args.allow_updates.get_inner(),
            allowed_to_leave: args.allowed_to_leave.get_inner(),
            auto_connect: args.auto_connect.get_inner(),
            captive_portal: args.captive_portal.get_inner(),
            default: args.default.get_inner(),
            description: args.description.get_inner(),
            disable_auto_fallback: args.disable_auto_fallback.get_inner(),
            enabled: args.enabled.get_inner(),
            exclude_office_ips: args.exclude_office_ips.get_inner(),
            match_: args.match_.get_inner(),
            name: args.name.get_inner(),
            precedence: args.precedence.get_inner(),
            service_mode_v2_mode: args.service_mode_v2_mode.get_inner(),
            service_mode_v2_port: args.service_mode_v2_port.get_inner(),
            support_url: args.support_url.get_inner(),
            switch_locked: args.switch_locked.get_inner(),
        },
    );

    DeviceSettingsPolicyResult {
        account_id: crate::into_domain(result.account_id),
        allow_mode_switch: crate::into_domain(result.allow_mode_switch),
        allow_updates: crate::into_domain(result.allow_updates),
        allowed_to_leave: crate::into_domain(result.allowed_to_leave),
        auto_connect: crate::into_domain(result.auto_connect),
        captive_portal: crate::into_domain(result.captive_portal),
        default: crate::into_domain(result.default),
        description: crate::into_domain(result.description),
        disable_auto_fallback: crate::into_domain(result.disable_auto_fallback),
        enabled: crate::into_domain(result.enabled),
        exclude_office_ips: crate::into_domain(result.exclude_office_ips),
        match_: crate::into_domain(result.match_),
        name: crate::into_domain(result.name),
        precedence: crate::into_domain(result.precedence),
        service_mode_v2_mode: crate::into_domain(result.service_mode_v2_mode),
        service_mode_v2_port: crate::into_domain(result.service_mode_v2_port),
        support_url: crate::into_domain(result.support_url),
        switch_locked: crate::into_domain(result.switch_locked),
    }
}
